[Interface]
Address = 10.10.100.1/24, 10.10.110.1/24
ListenPort = 51820
PrivateKey = sKE+WCZSJPovK+uEDuqvOqnqBRmJuy2MIyHZ6MIv4Vk=

PostUp = sysctl -w net.ipv4.ip_forward=1
PostUp = iptables -I FORWARD 1 -s 10.10.100.0/24 -d 10.10.10.0/24 -i wg0 -j DROP
PostUp = iptables -A FORWARD -s 10.10.100.0/24 -i wg0 -j ACCEPT
PostUp = iptables -A FORWARD -s 10.10.110.0/24 -i wg0 -j ACCEPT
PostUp = iptables -A FORWARD -o wg0 -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
PostUp = iptables -t nat -A POSTROUTING -s 10.10.100.0/24 -o eth0 -j MASQUERADE
PostUp = iptables -t nat -A POSTROUTING -s 10.10.110.0/24 -o eth0 -j MASQUERADE

PostDown = iptables -D FORWARD -s 10.10.100.0/24 -d 10.10.10.0/24 -i wg0 -j DROP
PostDown = iptables -D FORWARD -s 10.10.100.0/24 -i wg0 -j ACCEPT
PostDown = iptables -D FORWARD -s 10.10.110.0/24 -i wg0 -j ACCEPT
PostDown = iptables -D FORWARD -o wg0 -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
PostDown = iptables -t nat -D POSTROUTING -s 10.10.100.0/24 -o eth0 -j MASQUERADE
PostDown = iptables -t nat -D POSTROUTING -s 10.10.110.0/24 -o eth0 -j MASQUERADE
# BEGIN TG VPN MANAGED PEERS
# pavlik (889149235)
[Peer]
PublicKey = u8mWGgkkMzvdjrXmD4AuIf5nWLPUXZXxRPpyESBWNkk=
PresharedKey = V2zlggiyfIZpcWEUmxvR2o9JaGY0l6Z2+Aw7ykfO6Ms=
AllowedIPs = 10.10.100.102/32

# END TG VPN MANAGED PEERS








#[Peer]
#PublicKey = tVo2+Ltj97QtHwcv8HACtrGJMvZAR8X7bzfV5r9WM2I=
#AllowedIPs = 10.10.100.101/32
#PersistentKeepalive = 25
